### ISSUE TITLE
I can't find the blocklist file: 'static_data/app-flags.csv~test'.

### ISSUE THREAD

**Issue by willemkuijpers** [stopipv/isdi#28]
I can't find the blocklist file: 'static_data/app-flags.csv~test'.

**Comment by willemkuijpers** [comment]
can been closed

**Comment by lanamorgan** [comment]
This happens when isdi is run in test mode--when I got this error, I had to manually copy the app-flags.csv to a file called app-flags.csv~test. Not sure if there's another way to run this in test mode to ensure the correct file is created automatically or if we should have a permanent fix for it.

**Comment by rchatterjee** [comment]
You can create a symlink:  `ln -s ./data/app-flags.csv
./data/app-flags.csv~test`.
