### ISSUE TITLE
com.saurik.Cydia categorized as system app

### ISSUE THREAD

**Issue by drpomeranus** [stopipv/isdi#52]
The alternative App Store Cydia for jailbroken devices (com.saurik.Cydia) is falsely recognized as a system app by the isdi scan.

device: iPhone 8, running iOS 16

**Comment by rchatterjee** [comment]
I will add Cydia as dual-use,  off-regular application store app. This should flag it at the top (even though ISDi might think it as system app.)   When you get a chance can you check the new version to confirm?
