### ISSUE TITLE
iOS devices fail

### ISSUE THREAD

**Issue by qcassidy** [stopipv/isdi#9]
iOS devices continuously fail with message: `The scanning failed. This could be due to many reasons. Try rerunning the scan from the beginning.` The following exceptions are thrown in terminal: 

  - `Load_deviceinfo in parse_dump failed with exception InvalidFileException('Invalid file')`
  - `Exception>>> Command ''/Users/quinncassidy/Documents/GitHub/isdi/scripts/ios_dump.sh' 276408c373b576c4f858ff739f4f862ee4ededbc28df02a467f5c0f361c0512b ios_apps.plist ios_info.xml ios_jailbroken.log ios_jailbreak_ssh.retcode' timed out after 10 seconds`
  - `Could not load the json file: /Users/quinncassidy/Documents/GitHub/isdi/phone_dumps/276408c373b576c4f858ff739f4f862ee4ededbc28df02a467f5c0f361c0512b_ios/ios_apps.plist`

**Comment by JaySmith502** [comment]
Same issue

**Comment by Computer-Busters** [comment]
Scanner works with older iPhones but not newer ones. I have tested it with an iPhone 8 running iOS 14 and it works. However, it doesn't work with an iPhone 12 or 13 (both running iOS 15).

**Comment by rchatterjee** [comment]
It should work now with the new update. Please check.
